config/routes.rb
Rails.application.routes.draw do
  get 'parser/nokogiri'

  resources :universities
  resources :reports
  get 'welcome/index'

  get '/auswahl/', to: 'reports#auswahl'
  get '/general/', to: 'reports#general'
  get '/firsthalfyear/', to: 'reports#firsthalfyear'

  get '/kommentare/', to: 'reports#comments'

  get '/entries_of_universities', to: 'reports#entries_of_universities'

  get '/allcomments/', to: 'reports#allcomments'

  get '/nokogiri/', to: 'parser#nokogiri'

  get '/philosophieaktuell/', to: 'reports#philosophieaktuell'

  get '/blogger/', to: 'reports#blogger'

  get '/externalposts/', to: 'reports#externalposts'

  post '/addblogger/', to: 'reports#addblogger'

  get '/bloggercsv/', to: 'reports#bloggercsv'

  get '/liebeundgemeinschaft/', to: 'reports#liebeundgemeinschaft'

  root 'reports#auswahl'

  get '/ionic', to: 'ionic#ionic'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/university.rb
class University < ApplicationRecord
  belongs_to :report
  store_accessor :preferences
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_params
      params.fetch(:university, {})
    end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/helpers/university_helper.rb
module UniversityHelper
end

app/views/universities/_form.html.erb
<%= form_with(model: university, local: true) do |form| %>
  <% if university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% university.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Universities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universities.each do |university| %>
      <tr>
        <td><%= link_to 'Show', university %></td>
        <td><%= link_to 'Edit', edit_university_path(university) %></td>
        <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New University', new_university_path %>

app/views/universities/new.html.erb
<h1>New University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Back', universities_path %>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>