config/routes.rb
Rails.application.routes.draw do
  get 'parser/nokogiri'

  resources :universities
  resources :reports
  get 'welcome/index'

  get '/auswahl/', to: 'reports#auswahl'
  get '/general/', to: 'reports#general'
  get '/firsthalfyear/', to: 'reports#firsthalfyear'

  get '/kommentare/', to: 'reports#comments'

  get '/entries_of_universities', to: 'reports#entries_of_universities'

  get '/allcomments/', to: 'reports#allcomments'

  get '/nokogiri/', to: 'parser#nokogiri'

  get '/philosophieaktuell/', to: 'reports#philosophieaktuell'

  get '/blogger/', to: 'reports#blogger'

  get '/externalposts/', to: 'reports#externalposts'

  post '/addblogger/', to: 'reports#addblogger'

  get '/bloggercsv/', to: 'reports#bloggercsv'

  get '/liebeundgemeinschaft/', to: 'reports#liebeundgemeinschaft'

  root 'reports#auswahl'

  get '/ionic', to: 'ionic#ionic'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :universities
  store_accessor :general
  store_accessor :interests

  #primary keay #
  self.primary_key = "id"
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json

  def bloggercsv
    @bloggers = Blogger.all
    respond_to do |format|
      format.csv { send_data @bloggers.to_csv, filename: "Liste-Blogger.csv" }
    end
  end

  def blogger

  end

  def externalposts
    @externalposts = AlchemyPage.where(page_layout: "article").where.not(published_at: nil).all_except(Rails.configuration.philochlerids)
  end

  def comments

    if params[:language].nil?
      @comments = Comment.where.not(confirmed_at: nil)
    else
      lang_comments = []
      Comment.where.not(confirmed_at: nil).each do |comment|
      #Comment.all.each do |comment|
      #Comment.where("created_at > ?", Date.today - 7.days).each do |comment|


        if (AlchemyPage.where(id: comment.commentable_id).exists?) && (AlchemyPage.find(comment.commentable_id).language_code == params[:language])
          lang_comments.push(comment.id)

        end
      end
      @comments = Comment.where(id: lang_comments)
    end

    articles = []
    #@comments = Comment.where.not(confirmed_at: nil)

    Comment.where.not(confirmed_at: nil).each do |comment|
    #Comment.all.each do |comment|
    #Comment.where("created_at > ?", Date.today - 7.days).each do |comment|

      if AlchemyPage.where(id: comment.commentable_id).exists?
        puts comment.id
        articles.push(AlchemyPage.find(comment.commentable_id))
      end
    end

    articles = articles.uniq

    articles = AlchemyPage.where(id: articles.map(&:id))

    @articleswithcomments = articles.order(created_at: :desc)
  end

  def allcomments

    if params[:language].nil?
      @comments = Comment.all
    else
      lang_comments = []
      Comment.all.each do |comment|
      #Comment.all.each do |comment|
      #Comment.where("created_at > ?", Date.today - 7.days).each do |comment|


        if (AlchemyPage.where(id: comment.commentable_id).exists?) && (AlchemyPage.find(comment.commentable_id).language_code == params[:language])
          lang_comments.push(comment.id)

        end
      end
      @comments = Comment.where(id: lang_comments)
    end

    articles = []
    #@comments = Comment.where.not(confirmed_at: nil)

    Comment.where.not(confirmed_at: nil).each do |comment|
    #Comment.all.each do |comment|
    #Comment.where("created_at > ?", Date.today - 7.days).each do |comment|

      if AlchemyPage.where(id: comment.commentable_id).exists?
        puts comment.id
        articles.push(AlchemyPage.find(comment.commentable_id))
      end
    end

    articles = articles.uniq

    articles = AlchemyPage.where(id: articles.map(&:id))

    @articleswithcomments = articles.order(created_at: :desc)
  end

  def liebeundgemeinschaft
    articles = []
    @comments = Comment.where.not(confirmed_at: nil)

    aktuellarticles = getallarticleswithtag("Projekt Liebe und Gemeinschaft")

    Comment.where.not(confirmed_at: nil).each do |comment|
      #Comment.all.each do |comment|
      #Comment.where("created_at > ?", Date.today - 7.days).each do |comment|

      #if AlchemyPage.where(id: comment.commentable_id).exists?

      if aktuellarticles.where(id: comment.commentable_id).exists?
        articles.push(AlchemyPage.find(comment.commentable_id))
      end
    end

    articles = articles.uniq

    @articleswithcomments = articles
  end

  def philosophieaktuell
    articles = []
    #@comments = Comment.where.not(confirmed_at: nil)

    aktuellarticles = getallarticleswithtag("Projekt Philosophie aktuell")

    Comment.where.not(confirmed_at: nil).each do |comment|
      #Comment.all.each do |comment|
      #Comment.where("created_at > ?", Date.today - 7.days).each do |comment|

      #if AlchemyPage.where(id: comment.commentable_id).exists?

      if aktuellarticles.where(id: comment.commentable_id).exists?
        articles.push(AlchemyPage.find(comment.commentable_id))
      end
    end

    articles = articles.uniq

    @articleswithcomments = articles
  end

  def auswahl
    @firsthalfyear = Report.find_by_name("firsthalfyear")
    @thirdquarter = Report.find_by_name("thirdquarter")
    @secondhalfyear =  Report.find_by_name("secondhalfyear")
    @alltime = Report.find_by_name("alltime")
  end

  def firsthalfyear
    @report = Report.first
  end

  def general

   # @reports = Report.all

    #@interests = count_chosen_topics("member")

    #@generalinformation = analyze(Report.last)

#    @unis = Report.last.universities

 #   @stacked_interests = count_chosen_topics_stacked("member")

   # memberinos = {}
    #Report.all.order(:date).each do |report|
     # memberinos[report.date] = report.general["members"]
    #end
    #@memberinos = memberinos


  end

  def index
    @reports = Report.where(specialreport: false)

    @specialreports = Report.where(specialreport: true)


    @interests = count_chosen_topics("member")
  end

  # GET /reports/1
  # GET /reports/1.json
  def show

    gon.newsletteraktiv = @report

    gon.otherinstitutionschart = @report.societies

    allgemeingroupinterests = @report.allgemeingroupinterests.to_h

    gon.interesseallgemein = allgemeingroupinterests
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    analyze(@report)
    respond_to do |format|
      if @report.save

        unis(@report)
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def calculatenew(value, range)

  end


  def addblogger
    blogger_id = params[:blogger_id]
    blogger_interests = params[:blogger_interests]

    Blogger.create(blogger_id: blogger_id, interests: blogger_interests)

    redirect_to blogger_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:date)
    end

  def analyze(report)

    allprofiles = Profile.all.count
    members = AlchemyUser.where(alchemy_roles: "member").count
    institutions = AlchemyUser.where(alchemy_roles: "institution").count
    public = Profile.where(public: true).count
    private = Profile.where(public: false).count
    allgemein = Profile.where(level: 0).count
    expert = Profile.where(level: 1).count

    report.general = {
        allprofiles: allprofiles,
        members: members,
        institutions: institutions,
        public: public,
        private: private,
        allgemein: allgemein,
        expert: expert
    }

    return report.general

  end

  def unis(report)
    all_unis = Profile.all.distinct.pluck(:institutional_affiliation)
    all_unis.each do |uni|

      university = report.universities.create(title: uni)

      hash = {}

     types = Profile.where(institutional_affiliation: uni).pluck(:type_of_affiliation)

      types.each do |type|
        hash[type] = Profile.where(institutional_affiliation: uni).where(type_of_affiliation: type).count
      end

      university.information = hash

      university.save!

    end

  end

  def count_chosen_topics(scope = nil)
    all_topics = Topic.all.distinct.pluck(:name)
    hash_of_all_topics= {}
    all_topics.each{|a| hash_of_all_topics[a] = 0}


    Profile.all.each do |profile|

      if scope.nil?
        count_topics(profile, hash_of_all_topics)
      elsif AlchemyUser.find(profile.id).alchemy_roles == scope
        count_topics(profile, hash_of_all_topics)
      end

    end

    return hash_of_all_topics.sort {|a,b| a[1]<=>b[1]}.reverse
  end

  def count_chosen_topics_stacked(scope = nil)

    all_topics = Topic.all.distinct.pluck(:name)
    hash_of_all_topics= {}
    all_topics.each{|a| hash_of_all_topics[a] = 0}

    expert_data = hash_of_all_topics.clone
    allgemein_data = hash_of_all_topics.clone

    expert_array = []
    allgemein_array = []

    final_array = []

    Profile.all.each do |profile|

      if AlchemyUser.find(profile.id).alchemy_roles == scope
        if profile.level == 1
          count_topics(profile, expert_data)
        else
          count_topics(profile, allgemein_data)
        end
      end
    end

    ordered_array = count_chosen_topics(scope)
    logger.debug ordered_array.inspect

    ordered_array.each do |element|
      logger.debug element.inspect
      element[1] = expert_data[element[0]]
      logger.debug element.inspect
    end

    expert_array = ordered_array

    allgemein_data.each do |key, value|
      allgemein_array.push([key, value])
    end

    final_array = [
        {
            name: "Experten",
            data: expert_array
        },
        {
            name: "Allgemein",
            data: allgemein_array
        }
    ]

    return final_array
  end

  def count_all_profiles
    Profile.all.count
  end

app/helpers/reports_helper.rb
module ReportsHelper
  def countphilochler(list)

    philochler = 0
    # 7 = Sandro, 512 = Steve Wattson, 375 = kantumik, 513 = Hadron, 1 = Emanuel, 2 = Anja, 3 = Carole, 4 = Philipp
    # 5 = Franziska, 6 = Sahra, 8 = benjamin
    # philochlerids = [1,2,3,4,6,7,8, 512, 513, 375]
      philochlerids = Rails.configuration.philochlerids
    list.each do |comment|
      if philochlerids.include?(comment.user_id)
        philochler = philochler + 1
      end
    end

    philochler
  end

  def returnname(creator_id)
    #u = AlchemyUser.find(creator_id)
    if AlchemyUser.where(id: creator_id).present?
      u = AlchemyUser.find(creator_id)
      if !u.firstname.blank?
        u.firstname + " " + u.lastname
      else
        u.login
      end

    else
      "User nicht gefunden"
    end
  end
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :report_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_interests.html.erb
<h2>Interessensgebiete</h2>
<%= bar_chart [
                  {name: "Experten", data: report.stackedinterests[0]},
                  {name: "Allgemein", data: report.stackedinterests[1]}
              ], height: "1200px", stacked: true %>
<br>
<h2>Interessensgebiete Allgemein</h2>
<canvas id="interesseallgemein"></canvas>
<br>
<h2>Thementags</h2>
<%= bar_chart [
                  {name: "Artikel", data: report.articleanalysis.reverse.to_h},
                  {name: "Events", data: report.eventanalysis}
              ], height: "1500px", stacked: true %>

<script>
    horizontalBarWithLabel(gon.interesseallgemein, "interesseallgemein");
</script>

app/views/reports/_linecharts.html.erb
<br>
<h2>Benutzerprofile erstellt (Mitglieder): <%= report.profiletotal.to_a.last[1].to_i - report.profiletotal.first[1].to_i  %></h2>
<h3>Fluktuation</h3>
<%= line_chart report.profileerstellt %>
<br>
<h2>Benutzerprofile total: <%= report.profiletotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.profiletotal  %>
<br>
<h2>Kommentare erstellt: <%= report.kommentaretotal.to_a.last[1].to_i - report.kommentaretotal[report.startdate.to_s].to_i  %></h2>
<h3>Fluktuation</h3>
<%= line_chart report.kommentareerstellt %>
<br>
<h2>Kommentare total: <%= report.kommentaretotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.kommentaretotal  %>
<br>
<h2>Events erstellt: <%= report.eventstotal.to_a.last[1].to_i - report.eventstotal[report.startdate.to_s].to_i  %></h2>
<h3>Fluktuation</h3>
<%= line_chart report.eventserstellt %>
<br>
<h2>Events total: <%= report.eventstotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.eventstotal  %>
<br>
<h2>Artikel erstellt: <%= report.artikeltotal.to_a.last[1].to_i - report.artikeltotal[report.startdate.to_s].to_i  %></h2>
<h3>Fluktuation</h3>
<%= line_chart report.artikelerstellt %>
<br>
<h2>Artikel total: <%= report.artikeltotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.artikeltotal  %>
<br>
<h2>CfP erstellt: <%= report.cfptotal.to_a.last[1].to_i - report.cfptotal[report.startdate.to_s].to_i  %></h2>
<h3>Fluktuation</h3>
<%= line_chart report.cfperstellt %>
<br>
<h2>CfP total: <%= report.cfptotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.cfptotal  %>
<br>
<h2>Jobs erstellt: <%= report.jobstotal.to_a.last[1].to_i - report.jobstotal[report.startdate.to_s].to_i  %></h2>
<h3>Fluktuation</h3>
<%= line_chart report.jobserstellt %>
<br>
<h2>Jobs total: <%= report.jobstotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.jobstotal  %>
<br>
<br>
<h2>Lehrpersonen total: <%= report.lehrpersonentotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.lehrpersonentotal  %>
<br>
<br>
<h2>Interessierte in Weiterbildung total: <%= report.interestedineducationtotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.interestedineducationtotal  %>
<br>
<h2>Newsletter bezogen: <%= report.newslettertotal.to_a.last[1].to_i - report.newslettertotal[report.startdate.to_s].to_i  %></h2>
<h3>Fluktuation</h3>
<%= line_chart report.newslettererstellt %>
<br>
<h2>Newsletter total: <%= report.newslettertotal.to_a.last[1] %></h2>
<h3>Entwicklung</h3>
<%= area_chart report.newslettertotal  %>
<br>

<h2>Newsletter aktiv</h2>
<%= column_chart({"Aktiv" => report.general["newsletteraktiv"] , "Total" => report.general["newslettertotal"]}, label: "Value") %>

app/views/reports/_newsletter.html.erb
<h1>Zuletzt angemeldet</h1>
<%= column_chart report.zuletztangemeldet %>

app/views/reports/_piecharts.html.erb
<h2>Benutzerprofile insgesamt: <%= report.general["allprofiles"] %></h2>

<%= pie_chart({"Mitglieder: #{report.general["members"]}" => report.general["members"], "Institutionen: #{report.general["institutions"]}" => report.general["institutions"]}, library: { pieSliceText: 'value' }, adapter: "google") %>
<br>
<%= pie_chart({"Öffentlich: #{report.general["public"]}" => report.general["public"], "Privat: #{report.general["private"]}" => report.general["private"]}, colors: ["green", "orange"], library: { pieSliceText: 'value' }, adapter: "google")%>
<br>
<%= pie_chart({"Allgemein: #{report.general["allgemein"]}" => report.general["allgemein"], "Experten: #{report.general["expert"]}" => report.general["expert"]}, colors: ["gray", "black"], library: { pieSliceText: 'value' }, adapter: "google") %>
<br>
<%= pie_chart({"Einer Uni zugehörig: #{report.general["belongtouni"]}" => report.general["belongtouni"], "Ohne Zugehörigkeit: #{report.general["belongtonouni"]}" => report.general["belongtonouni"]}, colors: ["yellow", "pink"], library: { pieSliceText: 'value' }, adapter: "google") %>
<br>
<%= pie_chart({"Deutsch: #{report.general["german"]}" => report.general["german"], "Französisch: #{report.general["french"]}" => report.general["french"]}, colors: ["violet", "brown"], library: { pieSliceText: 'value' }, adapter: "google") %>
<br>

app/views/reports/blogger.html.erb
<br>
<div class="form-group pull-right">
  <input type="text" class="search form-control" placeholder="Nach Mitglied suchen">
</div>

<h1>Interessierte (die noch keinen Account haben)</h1>

<span class="counter pull-right"></span>
<table class="table table-hover table-bordered results">
  <thead>
  <tr>
    <th class="col-md-3 col-xs-3">Name</th>
  </tr>
  <tr class="warning no-result">
    <td colspan="4"><i class="fa fa-warning"></i> No result</td>
  </tr>
  </thead>
  <tbody>

  <tr>
    <td>Dominik Wedber</td>
  </tr>
  <tr>
    <td>
      Gregor Schäfer
    </td>
  </tr>
      <tr>
        <td>Michaela Abdelhamid</td>
      </tr>

  </tbody>
</table>

<h1>Blogger</h1>

<span class="counter pull-right"></span>
<table class="table table-hover table-bordered results">
  <thead>
  <tr>
    <th class="col-md-1">#</th>
    <th class="col-md-2">Blogger</th>
    <th class="col-md-1">Anzahl Beiträge</th>
    <th class="col-md-2">Interessensgebiet</th>
    <th class="col-md-2">Letzter Beitrag erstellt</th>
    <th class="col-md-2">Abgemachte Deadline</th>
    <th class="col-md-2">Beitrag abgegeben?</th>
  </tr>
  <tr class="warning no-result">
    <td colspan="4"><i class="fa fa-warning"></i> No result</td>
  </tr>
  </thead>
  <tbody>
  <% ids = Blogger.all.pluck(:blogger_id) %>
  <% Blogger.all.each do |blogger| %>
      <tr>
        <th scope="row"><%= blogger.blogger_id %></th>
        <td>
          <%= blogger.name %> -  <%= blogger.loginname %></td>
        <td>
          <%= blogger.entriescount %>
        </td>
        <td>
          <%= blogger.interests %>
        </td>
        <td>
          <%= blogger.lastentry %>
        </td>

        <td class="<%=blogger.deadlinestatus%>">
          <%= blogger.deadline %>
        </td>

        <td>
          <%= blogger.submittedblog? %>
        </td>
      </tr>


  <% end %>

  </tbody>
</table>

<h1>Mitglieder von Philosophie.ch, aber keine Blogger</h1>

<span class="counter pull-right"></span>
<table class="table table-hover table-bordered results">
  <thead>
  <tr>
    <th>#</th>
    <th class="col-md-4 col-xs-4">Mitglied</th>
    <th class="col-md-4 col-xs-4">Benutzername</th>
    <th class="col-md-4 col-xs-4"></th>
  </tr>
  <tr class="warning no-result">
    <td colspan="4"><i class="fa fa-warning"></i> No result</td>
  </tr>
  </thead>
  <tbody>


  <% AlchemyUser.where.not(id: ids).where(alchemy_roles: "member").each do |member| %>
    <% id = member.id %>
      <tr>
        <th scope="row"><%= id %></th>
        <td><%= member.firstname %> <%= member.lastname %></td>
        <td>
          <%= member.login %>
        </td>
        <td>
          <%= form_tag("/addblogger", method: "post") do %>
              <%= label_tag(:blogger_interests, "Interessensgebiet:") %>
              <%= text_field_tag(:blogger_interests) %>
              <%= hidden_field_tag :blogger_id, member.id %>
              <br>
              <br>
              <%= submit_tag"Als Blogger hinzufügen", class: "btn btn-primary" %>
          <% end %>
        </td>
      </tr>


  <% end %>

  </tbody>
</table>


<script>
    $(document).ready(function() {
        $(".search").keyup(function () {
            var searchTerm = $(".search").val();
            var listItem = $('.results tbody').children('tr');
            var searchSplit = searchTerm.replace(/ /g, "'):containsi('")

            $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
                return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
            }
            });

            $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
                $(this).attr('visible','false');
            });

            $(".results tbody tr:containsi('" + searchSplit + "')").each(function(e){
                $(this).attr('visible','true');
            });

            var jobCount = $('.results tbody tr[visible="true"]').length;
            $('.counter').text(jobCount + ' item');

            if(jobCount == '0') {$('.no-result').show();}
            else {$('.no-result').hide();}
        });
    });
</script>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/entries_of_universities.html.erb
<% all_uni_names = Profile.all.distinct.pluck(:institutional_affiliation) %>

<% all_uni_names.delete("") %>

<% all_uni_names.inspect %>

<% uni_accounts = AlchemyUser.where(alchemy_roles: "institution").order(:created_at) %>

<% uni_accounts.each do |uni| %>
  <h1><%= Profile.find(uni.id).name %><br /></h1>
  <b>Eingetragene Events: </b> <%= AlchemyPage.where(page_layout: "event", creator_id: uni.id).count %><br />
  <b>Eingetragene Stellenangebote: </b> <%= AlchemyPage.where(page_layout: "job", creator_id: uni.id).count  %><br />
  <b>Eingetragene CfP: </b> <%= AlchemyPage.where(page_layout: "call_for_papers", creator_id: uni.id).count %><br />
  <br />

  <h3>Events: </h3>
  <%= line_chart AlchemyPage.where(page_layout: "event", creator_id: uni.id).group_by_week(:created_at).count %>
  <hr />
  <h3>Stellenangebote: </h3>
  <%= line_chart AlchemyPage.where(page_layout: "job", creator_id: uni.id).group_by_month(:created_at).count %>
  <hr />
  <h3>CfP: </h3>
  <%= line_chart AlchemyPage.where(page_layout: "call_for_papers", creator_id: uni.id).group_by_week(:created_at).count %>
  <hr />
<% end %>

app/views/reports/externalposts.html.erb
<div class="form-group pull-right">
  <input type="text" class="search form-control" placeholder="What you looking for?">
</div>
<span class="counter pull-right"></span>
<table class="table table-hover table-bordered results">
  <thead>
  <tr>
    <th>#</th>
    <th class="col-md-5 col-xs-5">Artikel</th>
    <th class="col-md-4 col-xs-4">Autor</th>
    <th class="col-md-4 col-xs-4">Autor-ID</th>
  </tr>
  <tr class="warning no-result">
    <td colspan="4"><i class="fa fa-warning"></i> No result</td>
  </tr>
  </thead>
  <tbody>


  <% @externalposts.each do |article| %>

      <% comments = Comment.where.not(confirmed_at: nil).where(commentable_id: article.id) %>

      <tr>
        <th scope="row"><%= article.id %></th>
        <td><%= article.name %></td>
        <td><%= returnname(article.creator_id) %></td>
        <td><%= article.creator_id %></td>
      </tr>


  <% end %>

  </tbody>
</table>


<script>
    $(document).ready(function() {
        $(".search").keyup(function () {
            var searchTerm = $(".search").val();
            var listItem = $('.results tbody').children('tr');
            var searchSplit = searchTerm.replace(/ /g, "'):containsi('")

            $.extend($.expr[':'], {'containsi': function(elem, i, match, array){
                return (elem.textContent || elem.innerText || '').toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
            }
            });

            $(".results tbody tr").not(":containsi('" + searchSplit + "')").each(function(e){
                $(this).attr('visible','false');
            });

            $(".results tbody tr:containsi('" + searchSplit + "')").each(function(e){
                $(this).attr('visible','true');
            });

            var jobCount = $('.results tbody tr[visible="true"]').length;
            $('.counter').text(jobCount + ' item');

            if(jobCount == '0') {$('.no-result').show();}
            else {$('.no-result').hide();}
        });
    });
</script>

app/views/reports/firsthalfyear.html.erb
<h1>Erstes Halbjahr</h1>

<%= render partial: "piecharts", locals: {report: @report} %>

<%= render partial: "linecharts", locals: {report: @report} %>

app/views/reports/general.html.erb
test
test

<% data = [['Task', 'Hours per Day'],
           ['Work',     11],
           ['Eat',      2],
           ['Commute',  2],
           ['Watch TV', 2],
           ['Sleep',    7]] %>

<%= pie_chart data, library: { pieSliceText: 'value' } %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>