config/routes.rb
Rails.application.routes.draw do
  get 'parser/nokogiri'

  resources :universities
  resources :reports
  get 'welcome/index'

  get '/auswahl/', to: 'reports#auswahl'
  get '/general/', to: 'reports#general'
  get '/firsthalfyear/', to: 'reports#firsthalfyear'

  get '/kommentare/', to: 'reports#comments'

  get '/entries_of_universities', to: 'reports#entries_of_universities'

  get '/allcomments/', to: 'reports#allcomments'

  get '/nokogiri/', to: 'parser#nokogiri'

  get '/philosophieaktuell/', to: 'reports#philosophieaktuell'

  get '/blogger/', to: 'reports#blogger'

  get '/externalposts/', to: 'reports#externalposts'

  post '/addblogger/', to: 'reports#addblogger'

  get '/bloggercsv/', to: 'reports#bloggercsv'

  get '/liebeundgemeinschaft/', to: 'reports#liebeundgemeinschaft'

  root 'reports#auswahl'

  get '/ionic', to: 'ionic#ionic'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reports</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= include_gon(:init => true) %>
    <%= Gon::Base.render_data({}) %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light mb-4"  style="background-color: #e3f2fd;">
    <%= link_to root_path do %>
        <div class="navbar-brand d-inline">- Report -</div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Reports", auswahl_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Kommentare", kommentare_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Philo aktuell", philosophieaktuell_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blogger", blogger_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Externe Posts", externalposts_path, class:"nav-link" %>
        </li>
      </ul>

    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <div class="m-5">
    &nbsp;
  </div>

  <div class="text-center fixed-bottom grey-bg p-2 navbar-light" style="background-color: #e3f2fd;">
    <%= link_to root_path do %>
        <div class="navbar-brand d-inline">- Report -</div>
    <% end %>
  </div>
  </body>
</html>